services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_2019
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WSM@@2024
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

volumes:
  sqlserver_data:
